name: C
on: [push, pull_request]
jobs:
  test:
    strategy:
      matrix:
        platform:
          - macos-latest
          - ubuntu-latest
        compiler:
          - clang
          - gcc
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Test
        run: make test CC=${{ matrix.compiler }}
        env:
          CC: ${{ matrix.compiler }}
